### ISSUE TITLE
`scoreboard.objectives.setDisplay` has inconsistent casing

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#119]
It should be `scoreboard.objectives.setdisplay`. Nothing else that I know of in the library takes the lowercase of vanilla Minecraft syntax and turns it into camel case where there are officially multiple words. For example, `datapack`, `gamerule`, `tellraw`, `playsound`, `teammsg`, `setworldspawn`, `gamemode`, etc. are all lowercase despite officially containing multiple words. So why isn't `setdisplay`?

**Comment by MulverineX** [comment]
Final sub-commands being camel case is an intended design choice.
