### ISSUE TITLE
`TimeArgument` type could be more precise

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#126]
Instead of `number | LiteralUnion<'1t' | '1s' | '1d'>`, it could be `` number | `${number}${'t' | 's' | 'd'}` `` (or something equally restrictive that still includes `'1t'`, `'1s'`, and `'1d'` as auto-complete options).

**Comment by TheMrZZ** [comment]
That's right! Didn't think about that. I'll change it.
