### ISSUE TITLE
`with` is `TextComponentObject[]` instead of `JSONTextComponent[]`

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#135]
I'm pretty sure this is a bug.

![image](https://user-images.githubusercontent.com/14056899/147420699-6f49f561-0859-4d72-ac87-431e3db0a0a8.png)

**Comment by MulverineX** [comment]
This is WAI

**Comment by GrantGryczan** [comment]
The wiki says `with` accepts any text component, not only objects:
![image](https://user-images.githubusercontent.com/14056899/221055494-243cea1e-4873-4ebf-ac96-098cda2a9dc7.png)
