### ISSUE TITLE
Incorrect output with empty `execute` `run` callback

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#145]
```ts
MCFunction('test', () => {
    execute.as('@s').run('something', () => {});
    say(1);
    say(2);
    say(3);
});
```

outputs

```mcfunction
execute as @s run say 1
say 2
say 3
```

This applies whether you specify the function name argument in `run` or not. Either way, it should create an empty function and run a `function` command there instead.

Similarly,

```ts
MCFunction('test', () => {
    execute.as('@s').run('something', () => {
        comment('test');
    });
    say(1);
    say(2);
    say(3);
});
```

outputs

```mcfunction
execute as @s run # test
say 1
say 2
say 3
```

**Comment by TheMrZZ** [comment]
While this is indeed invalid, I don't plan on fixing that. It's semantically invalid to do `execute run` anyway, so there is no reason it should work inside Sandstone.

Best thing would be to throw an error.

**Comment by GrantGryczan** [comment]
I don't know what you mean. This is an actual issue during development where I haven't necessarily filled up every function I've created yet.

**Comment by TheMrZZ** [comment]
Anyway, this will be fixed once I rewrite Sandstone's command backend. Same for incorrect line breaks that pop up in some commands.
