### ISSUE TITLE
`execute.if.score` and `execute.unless.score` do not accept `Score`s directly

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#155]
![image](https://user-images.githubusercontent.com/14056899/148364470-865df009-2566-4a10-a62c-48d3d2adb1eb.png)

**Comment by MulverineX** [comment]
Duplicate of #172

**Comment by GrantGryczan** [comment]
Do note that it might be relatively complicated compared to the other duplicates of #172 to generalize this, since `Score`s are one argument while their primitive counterparts are two.

**Comment by MulverineX** [comment]
It's already done ;D
