### ISSUE TITLE
Rename `Item` to `ItemCommand` (and probably do the same for other applicable classes for consistency)

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#169]
I want to make my own `Item` class for custom items, but Sandstone's existing `Item` class is making that troublesome in the auto-complete, and I don't think the name "`Item`" really represents what Sandstone's `Item` class is anyway. In other words, I don't think it's a good name either way, and it's conflicting with something I want to do, so I think it might as well be renamed?

**Comment by TheMrZZ** [comment]
That's what I've been doing in the new Sandstone backend! So it will be consistent for all commands in the future.

**Comment by MulverineX** [comment]
And you can always import under a shorter name if you want, sounds good 👍
